/**
 * Pure helpers for the chat-to-buy flow: parsing seller-entered option strings
 * and composing the prefilled WhatsApp order message.
 */

export interface OptionGroup {
  label: string | null;
  values: string[];
}

/**
 * Parses "Sizes: S, M, L · Colors: Red, Black" into selectable chip groups.
 * Group separators: "·", "|", or ";". Values separated by ",".
 * Plain text without ":" renders as a single unnamed group.
 */
export function parseOptions(raw: string): OptionGroup[] {
  return raw
    .split(/[·|;]/)
    .map((group) => group.trim())
    .filter(Boolean)
    .map((group) => {
      const colonIdx = group.indexOf(':');
      const label = colonIdx > 0 ? group.slice(0, colonIdx).trim() : null;
      const valuesRaw = colonIdx > 0 ? group.slice(colonIdx + 1) : group;
      const values = valuesRaw
        .split(',')
        .map((v) => v.trim())
        .filter(Boolean);
      return { label, values };
    })
    .filter((g) => g.values.length > 0);
}

export function buildOrderMessage(args: {
  productName: string;
  shopName: string;
  /** The price of the option chosen, not necessarily the product's base price. */
  price: number;
  productUrl: string;
  selections: Record<string, string>;
  /**
   * The priced option the buyer picked, when the product has any.
   *
   * Named first in the message and separately from the free-text selections,
   * because it is the one choice that changed the number being quoted — a
   * seller reading "Medium" next to ₹899 can confirm the order without opening
   * the listing to check which size costs what.
   */
  variantName?: string | null;
  inStock: boolean;
}): string {
  const { productName, shopName, price, productUrl, selections, variantName, inStock } = args;
  const picked = Object.entries(selections)
    .map(([label, value]) => (label === '_' ? value : `${label}: ${value}`))
    .join(', ');

  if (!inStock) {
    const which = variantName ? ` (${variantName})` : '';
    return `Hi! I'm interested in "${productName}"${which} from your shop "${shopName}" on Seyon. It shows as sold out — could you let me know when it's back in stock? ${productUrl}`;
  }

  const parts = [variantName, picked].filter(Boolean).join(', ');
  const optionsPart = parts ? ` (${parts})` : '';
  return `Hi! I want to order: ${productName}${optionsPart} — ₹${price.toFixed(2)} from "${shopName}" on Seyon. ${productUrl}`;
}

export interface CartOrderMessageItem {
  title: string;
  price: number;
  quantity: number;
  selections: Record<string, string>;
}

export function buildCartOrderMessage(args: {
  shopName: string;
  items: CartOrderMessageItem[];
  totalPrice: number;
  address?: {
    name?: string | null;
    addressLine1?: string | null;
    addressLine2?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
    phone?: string | null;
  } | null;
}): string {
  const { shopName, items, totalPrice, address } = args;
  let message = `Hi! I would like to place an order from your storefront "${shopName}" for the following items:\n\n`;

  items.forEach((item, index) => {
    message += `${index + 1}. *${item.title}*\n`;
    if (Object.keys(item.selections).length > 0) {
      const specs = Object.entries(item.selections)
        .map(([k, v]) => `${k}: ${v}`)
        .join(', ');
      message += `   _Options: ${specs}_\n`;
    }
    message += `   Qty: ${item.quantity} × ₹${item.price.toFixed(2)} = *₹${(item.quantity * item.price).toFixed(2)}*\n\n`;
  });

  message += `*Total Order Value:* ₹${totalPrice.toFixed(2)}\n`;

  // Append shipping address if saved
  const hasAddress = address && (address.addressLine1 || address.city || address.postalCode);
  if (hasAddress) {
    message += `\n*Delivery Details:*\n`;
    message += `Name: ${address.name || 'N/A'}\n`;
    message += `Address: ${[address.addressLine1, address.addressLine2].filter(Boolean).join(', ')}\n`;
    message += `City/State: ${[address.city, address.state].filter(Boolean).join(', ')} - ${address.postalCode || ''}\n`;
    if (address.phone) {
      message += `Contact: ${address.phone}\n`;
    }
  } else {
    message += `\n(I will provide my delivery address during our chat.)\n`;
  }

  message += `\n-- Generated by Seyon Cart v1`;
  return message;
}

